### PR TITLE
New new build

### LINKED ISSUE #48: Crazy Dennis movement
The dialogue before Crazy Dennis' last phase is actually just a ploy to give him enough time to finish his movement cycle before the last phase. If the player goes through the dialogue quickly enough, it takes him an awkward couple seconds to get into position. Making it so he ends his phase 1/2 movement cycle and just lerps to his phase 3 position immediately after the player beats phase 2 would be cool.

### PR DESCRIPTION
**Pull request by smallwoj**
- Updated credits/other places
- Updated the unity version to 2021.3.35f1
- Fixed #48 
- Confirmed functionality by making sure a new build can be created (will upload to itch.io after merge)

### CODE REVIEW

**Review by drkitt — DISMISSED** [review]
LGTM I think! I don't wanna reinstall Unity and I trust you enough for me to just rubber-stamp this. I'll check out the build once it's uploaded to Itch though.

**Comment by smallwoj** [comment]
Oops didn't mean to dismiss the review, I ran the build and deployed it to https://crazy-tennis-build.toastlord.com/ if you wanted to take a look, it's looking good from here so once approved I will merge and deploy it to itch.io

**Review by drkitt — APPROVED** [review]
LGTM for real this time 😎

**Comment by smallwoj** [comment]
Uploaded!

**Pull request merged**
